sudo: false
language: node_js
node_js:
  - 10 # use nodejs v10 LTS
cache: npm
branches:
  only:
    - develop # build develop branch only
script:
  - hexo generate # generate static files
deploy:
  provider: pages
  verbose: true
  skip_cleanup: true
  github_token: $GH_TOKEN
  keep_history: true
  target_branch: master # GitHub Page's files must be in master branch
  on:
    branch: develop
  local_dir: public